name: Update Language Stats

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
          
      - name: Get repository list
        run: gh repo list DulshanSiriwardhana --json nameWithOwner --limit 10 > repositories.json

      - name: Fetch repository language stats
        run: |
          cat repositories.json | jq -r '.[].nameWithOwner' | while read repo; do
            gh api "/repos/$repo/languages" -q | jq -r 'to_entries[] | [.key, .value] | @tsv' >> languages.tsv
          done

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update language stats"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          branch: ${{ github.ref }}
